package hotelapp;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout; 
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**_
 *                            [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .i;9p---
 * @author EmoshiogweOmokhudu9
 */
public class RoomManagementGUI extends JFrame {
      private ArrayList<Room>rooms;
      private DefaultTableModel tableModel;
    /**
     * Creates new form RoomManagement
     */
    public RoomManagementGUI() {
        initComponents();
        setTitle("Room Management");
        setSize(900,600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        //ArrayList is used to store multiple Romm objects 
        rooms = new ArrayList<>();
        
        tableModel = (DefaultTableModel) tablemodel.getModel();
        tableModel.setRowCount(0);
        
        loadSampleData();
    
    }
    
    private void buildGUI(){
        JPanel mainPanel = new JPanel(new BorderLayout());
        
        //Title
        JLabel titleLabel = new JLabel("Room Management" , JLabel.CENTER);
        titleLabel.setFont(new Font("Arial",Font.BOLD,20));
        mainPanel.add(titleLabel,BorderLayout.NORTH);
        
        //Table for rooms
        String[] columns = {"Room ID", "Type", "Price", "Available"};
        tableModel = new DefaultTableModel(columns,0);
        tablemodel = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(tablemodel);
                mainPanel.add(scrollPane,BorderLayout.CENTER);
                
                //Button Panel
                JPanel buttonPanel = new JPanel(new FlowLayout());
                
                JButton addBtn = new JButton("Add Room");
                JButton editBtn = new JButton("Edit Room");
                JButton deleteBtn = new JButton ("Delete Room");
                JButton searchBtn = new JButton ("Search Room");
                JButton toggleBtn = new JButton (" Toggle Availability");
                JButton backBtn = new JButton ("Back to Main");
                
            
                buttonPanel.add(addBtn);
                buttonPanel.add(editBtn);
                buttonPanel.add(deleteBtn);
                buttonPanel.add(searchBtn);  
                buttonPanel.add(toggleBtn);
                buttonPanel.add(backBtn);  
                    
                mainPanel.add(buttonPanel, BorderLayout.SOUTH);
                
                add(mainPanel);
                
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addbtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        BackToMainbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemodel = new javax.swing.JTable();
        ToggleAvailabilityBtn = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addbtn.setText("Add Room");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit Room");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        Deletebtn.setText("Delete Room");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        BackToMainbtn.setText("Back to Main");
        BackToMainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMainbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Room Management");

        tablemodel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Type", "Price", "Availability"
            }
        ));
        jScrollPane1.setViewportView(tablemodel);

        ToggleAvailabilityBtn.setText("Availability");
        ToggleAvailabilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleAvailabilityBtnActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search Room");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(SearchBtn);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addGap(36, 36, 36)
                                .addComponent(EditBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Deletebtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToggleAvailabilityBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BackToMainbtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(EditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleAvailabilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackToMainbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // Creates a new Room object using user input and adds it to the ArrayList.
        // After adding, the table is refreshed so the user can see new room.
        JDialog addDialog = new JDialog(this, "Add New Room",true);
        addDialog.setSize(400,250);
        addDialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(5, 2, 10, 10));
        JTextField idField = new JTextField();
        JTextField typeField = new JTextField();
        JTextField priceField = new JTextField();
        JCheckBox availableCheckbox = new JCheckBox("Available", true);
        
        
        formPanel.add(new JLabel("Room ID:"));
        formPanel.add(idField);
         formPanel.add(new JLabel("Room type:"));
        formPanel.add(typeField);
        formPanel.add(new JLabel("Price:"));
        formPanel.add(priceField);
        formPanel.add(new JLabel("Available:"));
        formPanel.add(availableCheckbox);
        
        JButton saveBtn = new JButton("Save");
        JButton cancelBtn = new JButton("Cancel");
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(saveBtn);
        buttonPanel.add(cancelBtn);
        
        addDialog.setLayout(new BorderLayout());
        addDialog.add(formPanel, BorderLayout.CENTER);
        addDialog.add(buttonPanel, BorderLayout.SOUTH);
        
        saveBtn.addActionListener(new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e){
         try{
             String roomId = idField.getText().trim();
             String type = typeField.getText();
             double price = Double.parseDouble(priceField.getText());
             boolean available = availableCheckbox.isSelected();
             
             Room newRoom = new Room(roomId, type, price, available);
             rooms.add(newRoom);
             updateTable();
             addDialog.dispose();
             JOptionPane.showMessageDialog(RoomManagementGUI.this, "Room added successfully!");
             
         }catch (NumberFormatException ex){
             JOptionPane.showMessageDialog(RoomManagementGUI.this, "Please enter a valid price");
         }
         }
        });
        
        cancelBtn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                addDialog.dispose();
            }
        });
        
        addDialog.setVisible(true);
        
        
    }                                      

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Removes the selected Room object from ArrayList.
        //After deleting it updateTable() Refreshes the Jtable 
        int selectedRow = tablemodel.getSelectedRow();
        if (selectedRow >=0){
            rooms.remove(selectedRow);
            updateTable();
            JOptionPane.showMessageDialog(this, "Room deleted successfully!");
          }else{
          JOptionPane.showMessageDialog(this, "Please select a room to a delete");
          
         ;
        }
    }                                         

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // Allows the user to modify any room object.
        // The selected Room is updated directly inside the ArrayList
        // and the the table is refreshed to show changes
        
        int selectedRow = tablemodel.getSelectedRow();
        
        if (selectedRow <0){
        JOptionPane.showMessageDialog(this, "Please select a room to edit");
        return;
        }
        Room room = rooms.get(selectedRow);
        final int rowIndex = selectedRow;
        
        JDialog editDialog = new JDialog(this,"Edit Room", true);
        editDialog.setSize(400, 250);
        editDialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(4, 2, 10, 10));
        JTextField idField = new JTextField(room.getRoomID());
        JTextField typeField = new JTextField(room.getType());
        JTextField priceField = new JTextField(String.valueOf((char) room.getPrice()));
        JCheckBox availableCheckbox = new JCheckBox("Available", room.isAvailable());
        
        formPanel.add(new JLabel("Room ID:"));
        formPanel.add(idField);
        formPanel.add(new JLabel("Room Type:"));
        formPanel.add(typeField);
        formPanel.add(new JLabel("Price:"));
        formPanel.add(priceField);
        formPanel.add(new JLabel("Available:"));
        formPanel.add(availableCheckbox);
        
     
        
        JButton saveBtn = new JButton("Save");
        JButton cancelBtn = new JButton("Cancel");
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(saveBtn);
        buttonPanel.add(cancelBtn);
        
        editDialog.setLayout(new BorderLayout());
        editDialog.add(formPanel, BorderLayout.CENTER);
        editDialog.add(buttonPanel, BorderLayout.SOUTH);
        
        saveBtn.addActionListener(new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e){
         try{
             String newId = idField.getText().trim();
             String newType = typeField.getText().trim();
             String priceText = priceField.getText().trim();
             boolean newAvailable = availableCheckbox.isSelected();
            
             if (newId.isEmpty() || newType.isEmpty() || priceText.isEmpty()){
              JOptionPane.showMessageDialog(editDialog, "all fields are required! ");  
              return;
             }
             
             double newPrice = Double.parseDouble(priceText);
             
             for(int i = 0; i < rooms.size(); i ++){
             if (i == rowIndex) continue;
             if (rooms.get(i).getRoomID().equalsIgnoreCase(newId)){
             JOptionPane.showMessageDialog(editDialog, "Room ID already exist! ");
             return;
                 
             }
         }
            
             room.setRoomID(newId);
             room.setType(newType);
             room.setPrice(newPrice);
             room.setAvailable(newAvailable);
             updateTable();
             editDialog.dispose();
             JOptionPane.showMessageDialog(RoomManagementGUI.this, "Room updated successfully!");
             
         }catch (NumberFormatException ex){
             JOptionPane.showMessageDialog(editDialog, "Please enter a valid numberic price");
         }
         }
        });
        
        cancelBtn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                editDialog.dispose();
            }
        });
        
        editDialog.setVisible(true);
        
        
    }                                       

    private void ToggleAvailabilityBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // Toggles the Availability of the selected Room object
       
        int selectedRow = tablemodel.getSelectedRow();
        if (selectedRow >= 0){
           Room room = rooms.get(selectedRow);
           room.setAvailable(!room.isAvailable());
           updateTable();
         
           JOptionPane.showMessageDialog(this, "Room availability updated!");
           }else{
           JOptionPane.showMessageDialog(this, "Please select a room");
        }
    }                                                     

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Searches the ArrayList for a room object woth matching ID
        //if found will show  room details 
        String roomId = JOptionPane.showInputDialog(this,"Enter Room ID(e.g R101):");
        
        if (roomId == null || roomId.trim().isEmpty()){
            return; // user cancelled
        }
        
        boolean found = false;
        int foundIndex = -1;
        Room foundRoom = null;
        
        for(int i = 0; i < rooms.size(); i++){
            Room r = rooms.get(i);
            if(r.getRoomID().equalsIgnoreCase(roomId.trim())){
                found = true;
                foundIndex = i;
                foundRoom = r;
                break;
            }
            
        }
        if (found){
            tablemodel.setRowSelectionInterval(foundIndex, foundIndex);
            JOptionPane.showMessageDialog(this,
                 "Room found:\n" +
                 "ID:" +foundRoom.getRoomID()+ "\n"+
                 "Type:" +foundRoom.getType()+ "\n"+
                 "Price:" +foundRoom.getPrice()+ "\n"+
                 "Available:" +foundRoom.isAvailable());
                 }else{
             JOptionPane.showMessageDialog(this,"No room found with ID:" + roomId);
                     
        }
    }                                         

    private void BackToMainbtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        new mainPageJFrame().setVisible(true);
        this.dispose();
    }                                             

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        updateTable();
        
        RoomSaver saver = new RoomSaver(rooms);
        String summary = saver.buldsSaveSummary();
        JOptionPane.showMessageDialog(this, "Changes saved!" +summary);
    }                                       
    
    //Updates the Jtable by converting the ArrayList of Room Objects 
    // into rows for the table. This displays the current state of the data.
    private void updateTable(){
        tableModel.setRowCount(0);
        
        Room[] roomArray = rooms.toArray(new Room[0]);
        for(Room room : roomArray){
            tableModel.addRow(new Object[]{
                      room.getRoomID(),
                      room.getType(),
                      String.format("$%.2f", room.getPrice()),
                      room.isAvailable() ? "Available" : "Not Available"
        });
        }
    }
    
    //Adds initial Room objects in to the ArrayList for Testing the GUI
    // This shows the Data
    private void loadSampleData(){
        rooms.add(new Room("R101", "Single", 99.99, true));
        rooms.add(new Room("R102", "Double", 149.99, true));
        rooms.add(new Room("R103", "Suite", 299.99, false));
        updateTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomManagementGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BackToMainbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JToggleButton ToggleAvailabilityBtn;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tablemodel;
    // End of variables declaration                   
}
